spring:
  profiles:
    active: local
  application:
    name: "generic-model"

  config:
    import: "openapi.yml"

  jpa:
    open-in-view: false

genericmodel:
  api:
    default-page: 0
    default-page-size: 10
    max-page-size: 50
