spring:

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
      config:
        enabled: false
      token: "d8093229-2738-2ce7-5355-936fb1c34322"

  datasource:
    url: jdbc:mysql://localhost:3306/cookplan
    username: root
    password: dictionary

  jpa:
    hibernate:
      ddl-auto=: update
