name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
